### ISSUE TITLE
Confirmation called for the second time should be user error

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#186]
```
{
    event: {
        requestId: ...
        function: developer-portal-v2-prod-auth
        httpMethod: GET
        path: /auth/confirm/xxx/721673
        apiRequestId: ...
        ipAddress: ...
        userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
    }
    statusCode: 500
    error: {
        name: NotAuthorizedException
        message: User cannot confirm because user status is not UNCONFIRMED.
        stack: {
            0: NotAuthorizedException: User cannot confirm because user status is not UNCONFIRMED.
            1:     at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
            2:     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
            3:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
            4:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
            5:     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
            6:     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
            7:     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
            8:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
            9:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
            10:     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
            11:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
            12:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
            13:     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
            14:     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
            15:     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
            16:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
        }
    }
}
```

**Comment by JakubMatejka** [comment]
Fixed

**Comment by RaphiStein** [comment]
How?
