### ISSUE TITLE
User cannot confirm because user status is not UNCONFIRMED.

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#191]
Dnes se objevilo pár chyb:
https://papertrailapp.com/events?q=0d9a140a-228b-11e8-9b74-35e3ebaa25dd
```
Mar 05 22:30:58 developer-portal-v2 prod:  {
event: {
requestId: 7dc0fbe3-20bc-11e8-be8a-e39ca45a4c87
function: developer-portal-v2-prod-auth
httpMethod: GET
path: /auth/confirm/XXXXX/839496
apiRequestId: 7dc19907-20bc-11e8-9206-85f78a255ae5
ipAddress: XXX
userAgent: XXX
}
statusCode: 500
error: {
name: NotAuthorizedException
message: User cannot confirm because user status is not UNCONFIRMED.
stack: {
0: NotAuthorizedException: User cannot confirm because user status is not UNCONFIRMED.
1:     at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
2:     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
3:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
4:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
5:     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
6:     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
7:     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
8:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
9:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
10:     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
11:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
12:     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
13:     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
14:     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
15:     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
16:     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
}
}
}
```

**Comment by Halama** [comment]
asi by mělo být jako user error. Nevím teda jak k tomu došlo, asi kliknul na potvrzení vícekrát?

**Comment by JakubMatejka** [comment]
Aha, jj. už to tu mám: https://github.com/keboola/developer-portal/issues/186 Podívám se na to.

**Comment by Halama** [comment]
sorry, to jsem přehlédl
