### ISSUE TITLE
Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#292]
```
{
    event: {
        requestId: 3a47eab3-0f1b-4e68-b093-b29f8c112fc9
        function: developer-portal-v2-prod-admin
        httpMethod: GET
        path: /admin/apps/peta-sittek.ex-adocean
        apiRequestId: 76eb5f38-4e8e-11e9-8dbc-318b741a456c
        ipAddress: 54.196.255.33
        userAgent: GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.1.27
    }
    statusCode: 500
    error: {
        name: Error
        message: Connection lost: The server closed the connection.
        stack: {
            0: Error: Connection lost: The server closed the connection.
            1:     at Protocol.end (/var/task/node_modules/mysql/lib/protocol/Protocol.js:112:13)
            2:     at TLSSocket.onend (_stream_readable.js:595:10)
            3:     at Object.onceWrapper (events.js:313:30)
            4:     at emitNone (events.js:111:20)
            5:     at TLSSocket.emit (events.js:208:7)
            6:     at endReadableNT (_stream_readable.js:1064:12)
            7:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
            8:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
            9:     --------------------
            10:     at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)
            11:     at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:200:25)
            12:     at Promise (/var/task/node_modules/serverless-mysql/index.js:185:23)
            13:     at new Promise (<anonymous>)
            14:     at Object.query (/var/task/node_modules/serverless-mysql/index.js:183:10)
            15:     at <anonymous>
        }
    }
}
```

**Comment by ondrejhlavacek** [comment]
a potom to ještě zahlásilo

> Mar 25 00:42:50 developer-portal-v2 us-east-1:147946154733:admin:  2019-03-24T23:42:49.941Z 3a47eab3-0f1b-4e68-b093-b29f8c112fc9 Task timed out after 30.03 seconds

**Comment by JakubMatejka** [comment]
Mělo by být ok (po upgradu serverless-mysql knihovny)
