### ISSUE TITLE
Internal error - Duplicate entry on PATCH /vendors/<vendorId>/<appId>

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#296]
https://keboola.slack.com/archives/C02CGK5CL/p1557481417075600
```
event: {
requestId: 5e04adc0-6fc3-4803-99c0-155f28ae7feb
function: developer-portal-v2-prod-apps
httpMethod: PATCH
path: /vendors/kds-team/apps/kds-team.ex-azure-blob
apiRequestId: 020e53b9-71ea-11e9-a23c-bd1e328d4f8c
userAgent: GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.3.1
}
statusCode: 500
error: {
name: Error
message: ER_DUP_ENTRY: Duplicate entry 'kds-team.ex-azure-blob-17' for key 'PRIMARY'
stack: {
0: Error: ER_DUP_ENTRY: Duplicate entry 'kds-team.ex-azure-blob-17' for key 'PRIMARY'
1:     at Query.Sequence._packetToError (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
2:     at Query.ErrorPacket (/var/task/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
3:     at Protocol._parsePacket (/var/task/node_modules/mysql/lib/protocol/Protocol.js:291:23)
4:     at Parser._parsePacket (/var/task/node_modules/mysql/lib/protocol/Parser.js:433:10)
5:     at Parser.write (/var/task/node_modules/mysql/lib/protocol/Parser.js:43:10)
6:     at Protocol.write (/var/task/node_modules/mysql/lib/protocol/Protocol.js:38:16)
7:     at TLSSocket.ondata (_stream_readable.js:639:20)
8:     at emitOne (events.js:116:13)
9:     at TLSSocket.emit (events.js:211:7)
10:     at addChunk (_stream_readable.js:263:12)
11:     at readableAddChunk (_stream_readable.js:250:11)
12:     at TLSSocket.Readable.push (_stream_readable.js:208:10)
13:     at TLSWrap.onread (net.js:607:20)
14:     --------------------
15:     at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)
16:     at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:201:25)
17:     at Promise (/var/task/node_modules/serverless-mysql/index.js:186:23)
18:     at new Promise (<anonymous>)
19:     at Object.query (/var/task/node_modules/serverless-mysql/index.js:184:10)
20:     at <anonymous>
21:     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by odinuv** [comment]
stejnej problem https://keboola.slack.com/archives/C02CGK5CL/p1557953387123300

**Comment by JakubMatejka** [comment]
Mno, vypadá to docela divně. V obou případech jde o stejnou appku (`kds-team.ex-azure-blob`) a přidávání verze `17` do tabulky `appVersions` (kde je PK na appId a verzi). Při tom appka má momentálně verzi 144 a zrovna v tom druhým včerejším případě tam během minuty vzniklo devět verzí (dvakrát dokonce ve stejné vteřině), který se v ničem neliší a přišlo to z nějakýho jejich servisního accountu pro Bitbucket.

**Comment by odinuv** [comment]
good point, jdu to zjistit co tam delaji, vypada to teda ale asi na nejakej race condition

**Comment by JakubMatejka** [comment]
Totéž se děje v `kds-team.ex-bluefox`
![devportalv2 — dev-portal prod 2019-05-16 11-43-54](https://user-images.githubusercontent.com/215660/57844336-21792080-77d0-11e9-8f5d-8bf40e2bcd1d.png)

**Comment by odinuv** [comment]
napadlo me, ze tam mozna maji nejakej skript na update props, ale uvidime co reknou

**Comment by odinuv** [comment]
jo, je to "legit"

short story: maji tam skript co updatuje props (ty se updatuji jednu po druhe), cili to na jeden release vyprodukuje ~5 updatu a leo neco testoval a misto na testovacim imagu to hazel do mastra
long story: https://keboola.zendesk.com/agent/tickets/10533
